name: ubuntu

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv with caching
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
    
    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Build project
      run: uv build
    
    - name: Run ruff
      run: uv run ruff check .
  
    - name: Run black
      run: uv run black .
    
    - name: Run tests
      run: uv run pytest tests
